# Generated by Django 2.2.19 on 2021-03-13 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=50)),
                ('ingredient', models.TextField()),
                ('procedure', models.TextField()),
                ('genre', models.IntegerField(help_text='1:麺, 2:丼, 3:主, 4:副, 5:汁')),
                ('country', models.IntegerField(help_text='1:和, 2:洋, 3:中, 4:伊, 5:他')),
                ('difficulty', models.IntegerField(help_text='1:楽々, 2:普通, 3:大変')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('link', models.URLField()),
                ('published_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
